name: ich_web
description: A new Flutter project.

# Environment setup specifying the minimum and maximum versions of the Dart SDK
environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies required for the project to function correctly
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.3.1
  dio: ^5.7.0
  flutter_lints: ^5.0.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/ID_9adc40048_Subdural.jpg
    - assets/ID_f26667baf_Epidural.jpg
    - assets/ID_cbe5d2ed7_Intraparenchymal.jpg
    - assets/ID_a8936e0de_Intraventricular.jpg
    - assets/ID_d5ab7d884_Subarachnoid.jpg
    - assets/ICH1.jpg
    - assets/Epidural.jpg
    - assets/Intraparenchymal.jpg
    - assets/Intraventricular.jpg
    - assets/Subarachnoid.jpg
    - assets/ICH2.jpg
    - assets/subdural1.jpg
    - assets/subdural2.jpg
    - assets/subdural3.jpg
    - assets/subdural4.jpg
    - assets/Intraventricular1.jpg
    - assets/Intraventricular2.jpg
    - assets/Intraventricular3.jpg
    - assets/Intraventricular4.jpg
    - assets/Intraparenchymal1.jpg
    - assets/Intraparenchymal2.jpg
    - assets/Intraparenchymal3.jpg
    - assets/Intraparenchymal4.jpg
    - assets/Subarachnoid1.jpg
    - assets/Subarachnoid2.jpg
    - assets/Subarachnoid3.jpg
    - assets/Subarachnoid4.jpg
    - assets/Epidural1.jpg
    - assets/Epidural2.jpg
    - assets/Epidural3.jpg
    - assets/Epidural4.jpg
    - assets/testing_web/ID_4af939e8d.dcm
    - assets/testing_web/ID_58e7e2e55.dcm
    - assets/testing_web/ID_cca25a801.dcm